export default [
    {
        id: 1,
        name: "The Student's Cultural House",
        sector: "Sector A",
        row: "Row 5",
        position: "Position F",
        time: "11:30 AM 04/10/2022",
        price: 5000,
    },
    {
        id: 2,
        name: "BCONS SUOI TIEN",
        sector: "Sector B",
        row: "Row 3",
        position: "Position A",
        time: "10:30 AM 05/10/2022",
        price: 5000,
    },
    {
        id: 3,
        name: "H2 - Ho Chi Minh City University Of Technology",
        sector: "Sector A",
        row: "Row 5",
        position: "Position F",
        time: "11:30 AM 04/10/2022",
        price: 5000,
    },
    {
        id: 4,
        name: "The Student's Cultural House",
        sector: "Sector A",
        row: "Row 5",
        position: "Position F",
        time: "11:30 AM 04/10/2022",
        price: 5000,
    },
    {
        id: 5,
        name: "H2 - Ho Chi Minh City University Of Technology",
        sector: "Sector A",
        row: "Row 5",
        position: "Position F",
        time: "11:30 AM 04/10/2022",
        price: 5000,
    },
    {
        id: 6,
        name: "The Student's Cultural House",
        sector: "Sector A",
        row: "Row 5",
        position: "Position F",
        time: "11:30 AM 04/10/2022",
        price: 5000,
    },
]